### ISSUE TITLE
Use app language setting for changeset comments

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#2581]
Mentioned briefly in #2577 

As I see it there are various pros and cons to changeset comments being in local language.

Pro: Changeset comments are more likely to match the language of the country they are in, making it easier for other local contributors to see what changes are being made

Con: Requires quite a bit of extra translation

Not a con: changeset comments being different for each quest depending on language, as there's still the "StreetComplete:quest_type" tag set on the changeset, which is unique per quest and would not be localised.

Personally I'm a native English speaker in an English speaking country, so it's not actually an issue for me, but wondered what people from other countries thought?

I'm happy to go through and make this change if it's something that's wanted, but definitely looking for feedback first.

**Comment by Helium314** [comment]
When you write 'local language' do you mean the (main?) language of the country where a quest is solved?
Or the language the phone (and thus StreetComplete) is set to?

Regarding the first, @matkoniecz pointed out some potential problems in https://github.com/streetcomplete/StreetComplete/issues/2577#issuecomment-779207518

And as for the second possibility, it might be problematic if someone living abroad has set his phone to their native language. This could lead to e.g. Greek changeset comments in Italy, which isn't going to make anyone happy.
Additionally @matkoniecz comment still applies partially

**Comment by matkoniecz** [comment]
Not sure what is better - occasional Greek changeset comments in Poland or English changeset comments all the time in Poland.

Include both? Still not sure is it worth implementation, review, maintenance and translation effort.

On the other hand, I understand English what is not true for everyone.

**Comment by FloEdelmann** [comment]
One fact to keep in mind: All tags and some (most?) values are English, too. Someone who reviews other people's changesets is thus likely to know at least a little English.

**Comment by arrival-spring** [comment]
> One fact to keep in mind: All OSM tags and some (most?) values are English, too. Someone who reviews other people's changesets is thus likely to know at least a little English.

True, hadn't really thought about that.
However, many editors that are used disguise the tags and values to an extent, although I'm not sure how that works when editing in other languages.

**Comment by matkoniecz** [comment]
> Someone who reviews other people's changesets is thus likely to know at least a little English.

Or just meaning of tags and check new ones on wiki (not sure how likely this scenario is)

**Comment by rhhsm** [comment]
I would be generating Dutch changeset comments in Bulgaria, so I think it should be either the language at the location of the quest, or English, or both. I don't think it's worth the effort of translation, though.

**Comment by mnalis** [comment]
Note that SC is mostly targeting to newbies (many of whom would have no idea what a changeset it, or where to look for it) so they are quite often not the target audience for changeset comments. Instead target audience are:

- software developers (trying to find all cases where some bug occurred, etc.) which would quite likely prefer the message to be the same in all cases (eg. not translated, so often in English).

- other users (usually more advanced) in the area which notice strange edits - as with leaving OSM Notes, the consensus there seems to be using language of the area being edited, or English.

Considering that, using language of the interface for changeset comment definitely sounds wrong. And using language of the area is also being problematic  (not only to developers, but there is also political issue in multi-language countries).

So I also think translating changeset comments would be introducing more problems than it would help. 
I would also leave it in English. (which also has a side benefit for developers and translators of not having to do any extra work, and so have more time to concentrate on important features)

(Note: I'm not an native English speaker. I've also done SC translation into my language)

**Comment by matkoniecz** [comment]
> software developers (trying to find all cases where some bug occurred, etc.) which would quite likely prefer the message to be the same in all cases (eg. not translated, so often in English).

For this changeset tags are sufficient - see https://www.openstreetmap.org/changeset/99399058

Changeset description is directed rather at people looking at history of object and people monitoring edits.

**Comment by westnordost** [comment]
Well, given the previous comments and there is no strong reason to add localized version of changeset comments, I'll close this as won't fix.
