### ISSUE TITLE
StreetComplete-0.5 crashes on starting

### ISSUE THREAD

**Issue by slackline** [streetcomplete/StreetComplete#97]
Hi,

After updating to v0.5 on 2017-03-30 StreetComplete crashes on starting under Android5.1 on a Samsung Galaxy GT-I9505G.  The following is a catlog output from filtering on 'street' (times match when I tried running StreetComplete).  If there is any more information required let me know.

I've nigh on zero experience of programming Android but it looks like the problem occurs at...

    04-05 08:16:30.852 E/AndroidRuntime(7019): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String de.westnordost.streetcomplete.data.QuestType.getIconName()' on a null object reference

The full catlog is...

    04-05 08:16:28.426 I/Timeline(10345): Timeline: Activity_launch_request id:de.westnordost.streetcomplete time:7499708
    04-05 08:16:28.427 I/ActivityManager(904): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.westnordost.streetcomplete/.MainActivity bnds=[291,351][525,611] (has extras)} from uid 10022 on display 0
    04-05 08:16:28.452 V/WindowManager(904): addAppToken: AppWindowToken{209549ed token=Token{247f6004 ActivityRecord{2ac03417 u0 de.westnordost.streetcomplete/.MainActivity t18430}}} to stack=1 task=18430 at 0
    04-05 08:16:28.461 V/WindowManager(904): Adding window Window{5ac9a5 u0 Starting de.westnordost.streetcomplete} at 14 of 18 (after Window{146a47c9 u0 com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity})
    04-05 08:16:28.572 I/ActivityManager(904): Start proc 7019:de.westnordost.streetcomplete/u0a157 for activity de.westnordost.streetcomplete/.MainActivity
    04-05 08:16:29.468 V/WindowManager(904): Adding window Window{28933064 u0 de.westnordost.streetcomplete/de.westnordost.streetcomplete.MainActivity} at 14 of 19 (before Window{5ac9a5 u0 Starting de.westnordost.streetcomplete})
    04-05 08:16:29.621 D/LocationManagerService(904): request 2a9f1782 gps Request[ACCURACY_FINE gps requested=+3m0s0ms fastest=+3m0s0ms] from de.westnordost.streetcomplete(10157)
    04-05 08:16:29.629 D/LocationManagerService(904): request 2a9f1782 network Request[POWER_LOW network requested=+3m0s0ms fastest=+3m0s0ms] from de.westnordost.streetcomplete(10157)
    04-05 08:16:29.671 D/LocationManagerService(904): request 2a9f1782 gps Request[ACCURACY_FINE gps requested=+3m0s0ms fastest=+3m0s0ms] from de.westnordost.streetcomplete(10157)
    04-05 08:16:29.672 D/LocationManagerService(904): request 2a9f1782 network Request[POWER_LOW network requested=+3m0s0ms fastest=+3m0s0ms] from de.westnordost.streetcomplete(10157)
    04-05 08:16:29.688 D/LocationManagerService(904): request 2a9f1782 gps Request[ACCURACY_FINE gps requested=+2s0ms fastest=+2s0ms] from de.westnordost.streetcomplete(10157)
    04-05 08:16:29.689 D/LocationManagerService(904): request 2a9f1782 network Request[POWER_LOW network requested=+2s0ms fastest=+2s0ms] from de.westnordost.streetcomplete(10157)
    04-05 08:16:29.812 I/ActivityManager(904): Displayed de.westnordost.streetcomplete/.MainActivity: +1s318ms
    04-05 08:16:29.813 I/Timeline(904): Timeline: Activity_windows_visible id: ActivityRecord{2ac03417 u0 de.westnordost.streetcomplete/.MainActivity t18430} time:7501094
    04-05 08:16:30.203 D/Tangram (7019): WARNING sceneLoader.cpp:1708: Can't find data source streetcomplete_quests for layer streetcomplete_quests
    04-05 08:16:30.203 D/Tangram (7019): WARNING sceneLoader.cpp:1708: Can't find data source streetcomplete_geometry for layer streetcomplete_geometry
    04-05 08:16:30.505 V/WindowManager(904): Adding window Window{3a557a94 u0 SurfaceView} at 14 of 19 (before Window{28933064 u0 de.westnordost.streetcomplete/de.westnordost.streetcomplete.MainActivity})
    04-05 08:16:30.566 I/Timeline(904): Timeline: Activity_windows_visible id: ActivityRecord{2ac03417 u0 de.westnordost.streetcomplete/.MainActivity t18430} time:7501847
    04-05 08:16:30.852 E/AndroidRuntime(7019): Process: de.westnordost.streetcomplete, PID: 7019
    04-05 08:16:30.852 E/AndroidRuntime(7019): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String de.westnordost.streetcomplete.data.QuestType.getIconName()' on a null object reference
    04-05 08:16:30.852 E/AndroidRuntime(7019): 	at de.westnordost.streetcomplete.tangram.QuestsMapFragment.addQuests(QuestsMapFragment.java:277)
    04-05 08:16:30.852 E/AndroidRuntime(7019): 	at de.westnordost.streetcomplete.MainActivity.onQuestsCreated(MainActivity.java:563)
    04-05 08:16:30.852 E/AndroidRuntime(7019): 	at de.westnordost.streetcomplete.data.VisibleQuestRelay.onQuestsCreated(VisibleQuestRelay.java:32)
    04-05 08:16:30.852 E/AndroidRuntime(7019): 	at de.westnordost.streetcomplete.data.QuestController$6.run(QuestController.java:230)
    04-05 08:16:30.917 W/ActivityManager(904):   Force finishing activity 1 de.westnordost.streetcomplete/.MainActivity
    04-05 08:16:32.208 W/PackageManager(3836): Failure retrieving resources for de.westnordost.streetcomplete: Resource ID #0x0
    04-05 08:16:33.328 I/ActivityManager(904): Process de.westnordost.streetcomplete (pid 7019) has died

**Comment by luca76** [comment]
It happens to me, too, on Huawei Honor 3C.

**Comment by westnordost** [comment]
This is fixed for the upcoming version 0.6. What you can do to fit it right now for yourself is to clear the app cache.

**Comment by slackline** [comment]
Great, good to hear you're on top of this.  Tried clearing app cache but still crashed, had to clear all data and re-authorise my OpenStreetMaps account details.

Thanks for writing and publishing the application, greatly simplifies contributing to OSM.

**Comment by westnordost** [comment]
Oh sorry, that's what I meant "clear all data", not just the cache. May bad.

**Comment by riQQ** [comment]
Duplicate of #55
